name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install pylint

      - name: Lint Python code
        run: |
          source venv/bin/activate
          pylint backend/**/*.py

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install Node.js dependencies
        run: |
          cd frontend
          npm install

      - name: Lint React code
        run: |
          cd frontend
          npm run lint
